name: "Build and Deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Restore
      run: dotnet restore TestLib

    - name: Build
      run: dotnet build TestLib --configuration Release --no-restore

    - name: Pack
      run: dotnet pack TestLib --configuration Release -o finalpackage --no-build

    # sign the NuGet Package -- can't do this without nuget.exe as dotnet CLI doesn't expose that
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: finalpackage

  deploy:
    needs: build
    name: Deploy Packages
    runs-on: ubuntu-latest
    steps:
      - name: Download Package artifact
        uses: actions/download-artifact@master
        with:
          name: nupkg

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
         nuget-version: latest

      - name: Setup NuGet GPR
        run: nuget source Add -Name "GPR" -Source ${{ secrets.GPR_URL }} -UserName ${{ secrets.GITHUB_USERNAME }} -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GPR
        run: nuget push nupkg/*.nupkg -Source "GPR" -SkipDuplicate